name: Getting Started Demo

on:
  [workflow_dispatch]
  
jobs:
  run_image:
    name: Run petclinic_app_build Image
    runs-on: ubuntu-latest
    container:
       image: anutkarudeha/petclinic_app_build:v3
    steps:
      - name: Fix Checkout
        run: |
          ldd --version

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Run the Docker image 
        run: |
          pwd
          ls
          export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto.x86_64"
          ./mvnw package

          pwd
          ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: petclinic_app_run
          path: target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: petclinic_app_run

      - uses: actions/upload-artifact@v4
        with:
          name: petclinic_db
          path: target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar

      - uses: actions/upload-artifact@v4
        with:
          name: artifact1
          path: petclinic_db

  build_image:
    needs: run_image
    name: Build petclinic_app_run Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          # path: target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar
      - run: |
          pwd
          ls

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/download-artifact@v4
        with:
          name: petclinic_app_run
      - name: Build image
        run: |
          pwd
          ls
          docker build -t anutkarudeha/petclinic_app_run:v1.5 -f petclinic_app_run .
          docker image push anutkarudeha/petclinic_app_run:v1.5

  run_dbimage:
    needs: build_image
    name: Run petclinic_db Image
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Run dbimage
        run: |
          pwd
          ls
          sudo chmod 777 /var/run/docker.sock
          docker run --name petclinic_db -p 3306:3306 --env MYSQL_USER=petclinic --env MYSQL_ROOT_PASSWORD=1234567890 --env MYSQL_DATABASE=petclinic --env MYSQL_PASSWORD=1234567890 --net mynet12 --ip 18.169.237.3 -d mysql:8.4.3
          docker images -a
          docker ps       

  run_apprun_image:
    needs: run_dbimage
    name: Run petclinic_app_run Image
    runs-on: [self-hosted, linux, x64]
    steps: 
      - name: Sleep for 0,5 minutes
        run: sleep 30s
        shell: bash

      - name: Run image
        run: |
          sudo chmod 777 /var/run/docker.sock
          docker run --net mynet12 --name petclinic_app -p 8080:8080 --env MYSQL_HOST=18.169.237.3 --env MYSQL_PORT=3306:3306 --env MYSQL_URL=jdbc:mysql://18.169.237.3:3306/petclinic --env MYSQL_DATABASE=petclinic --env MYSQL_USER=petclinic --env MYSQL_PASSWORD=1234567890 -d anutkarudeha/petclinic_app_run:v1.5
          docker images -a
          docker ps

# docker stop petclinic_db
# docker rm petclinic_db
# docker rm petclinic_app
#  docker run \
#        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
#

